# Generated by Django 2.1.7 on 2019-03-26 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0004_auto_20190316_1722'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stocks',
        ),
    ]
